# An example recipe that shows the creation of a user role.
name: 'Wunder next setup'
description: "Enable needed modules to use next-drupal and add pathauto setup"
type: 'Setup'
recipes:
  - wunder_pages
  - wunder_search
install:
  - next
  - next_jsonapi
  - pathauto
  - wunder_next
  - jsonapi_menu_items
  - jsonapi_extras
  - redirect
  - require_login
  - webform_rest
config:
  import:
    redirect: '*'
  actions:
    # Set the frontpage for the site:
    system.site:
      simple_config_update:
        page.front: '/admin/content'
    # Allow users to create accounts, and require email verification:
    user.settings:
      simple_config_update:
        register: 'visitors'
        verify_mail: true
    # Set permission to use register end point for anonymous user:
    user.role.anonymous:
      ensure_exists:
        label: 'Anonymous user'
      grantPermissions:
        - 'restful post user_registration'
